# name: Publish to NPM
# on:
#   release:
#     types: [created]

name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: pnpm install && pnpm run ci
      - name: Publish package on NPM 📦
        run: pnpm p18.1ublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}